# Generated by Django 2.0.4 on 2018-04-29 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('selectlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 16, 30, 10, 743657, tzinfo=utc)),
        ),
    ]
