# Generated by Django 2.0.4 on 2018-04-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectlist', '0002_auto_20180429_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
